package clientews.servicio;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import jakarta.xml.ws.WebEndpoint;
import jakarta.xml.ws.WebServiceClient;
import jakarta.xml.ws.WebServiceFeature;
import jakarta.xml.ws.Service;

/**
 * This class was generated by Apache CXF 4.0.4
 * 2025-03-21T12:58:05.908-06:00
 * Generated source version: 4.0.4
 *
 */
@WebServiceClient(name = "ServicioSumarImplService",
                  wsdlLocation = "http://localhost:8080/ServicioSumarImplService/ServicioSumarImpl?wsdl",
                  targetNamespace = "http://beans/")
public class ServicioSumarImplService extends Service {

    public static final URL WSDL_LOCATION;

    public static final QName SERVICE = new QName("http://beans/", "ServicioSumarImplService");
    public static final QName ServicioSumarImplPort = new QName("http://beans/", "ServicioSumarImplPort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:8080/ServicioSumarImplService/ServicioSumarImpl?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(ServicioSumarImplService.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "http://localhost:8080/ServicioSumarImplService/ServicioSumarImpl?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public ServicioSumarImplService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public ServicioSumarImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ServicioSumarImplService() {
        super(WSDL_LOCATION, SERVICE);
    }

    public ServicioSumarImplService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public ServicioSumarImplService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public ServicioSumarImplService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns ServicioSumarWS
     */
    @WebEndpoint(name = "ServicioSumarImplPort")
    public ServicioSumarWS getServicioSumarImplPort() {
        return super.getPort(ServicioSumarImplPort, ServicioSumarWS.class);
    }

    /**
     *
     * @param features
     *     A list of {@link jakarta.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ServicioSumarWS
     */
    @WebEndpoint(name = "ServicioSumarImplPort")
    public ServicioSumarWS getServicioSumarImplPort(WebServiceFeature... features) {
        return super.getPort(ServicioSumarImplPort, ServicioSumarWS.class, features);
    }

}
