package clientews.servicio;

import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.ws.Action;
import jakarta.xml.ws.RequestWrapper;
import jakarta.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 4.0.4
 * 2025-03-21T12:58:05.861-06:00
 * Generated source version: 4.0.4
 *
 */
@WebService(targetNamespace = "http://beans/", name = "ServicioSumarWS")
@XmlSeeAlso({ObjectFactory.class})
public interface ServicioSumarWS {

    @WebMethod
    @Action(input = "http://beans/ServicioSumarWS/sumarRequest", output = "http://beans/ServicioSumarWS/sumarResponse")
    @RequestWrapper(localName = "sumar", targetNamespace = "http://beans/", className = "clientews.servicio.Sumar")
    @ResponseWrapper(localName = "sumarResponse", targetNamespace = "http://beans/", className = "clientews.servicio.SumarResponse")
    @WebResult(name = "return", targetNamespace = "")
    public int sumar(

        @WebParam(name = "arg0", targetNamespace = "")
        int arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        int arg1
    );
}
